In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('train.txt', sep=';', header=None, names = ['text', 'emotions'])

In [5]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [7]:
unique_emotion = df['emotions'].unique()

In [8]:
emotion_number = {}
i = 0
for emo in emotion_number:
  emotion_number[emo] = i
  i+=1

  df['emotions'] = df['emotions'].map()

In [9]:
df

                                                    text emotions
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [10]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [11]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('', '', string.punctuation))

In [12]:
df['text'] = df['text'].apply(remove_punc)

In [13]:
def remove_number(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new + i
  return new

In [14]:
df['text'] = df['text'].apply(remove_number)

In [15]:
def remove_emoji(txt):
  new = ""
  for i in txt:
    if not i.isascii():
      new = new + i
  return new

In [16]:
df['text'] = df['text'].apply(remove_emoji)

In [17]:
import nltk

In [18]:
from nltk.corpus import stopwords

In [19]:
from nltk.tokenize import word_tokenize

In [20]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [21]:
stop_words = set(stopwords.words('english'))

In [22]:
def remove(txt):
  word = txt.split()
  cleaned = []
  for i in word:
    if i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [23]:
df['text'] = df['text'].apply(remove)